development:
  adapter: mysql2
  database: facebook_development
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: facebook_test
  pool: 5
  username: root
  password:
  timeout: 5000
